version: 1

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin

archives:
  - files:
      - LICENSE
      - README.md
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    wrap_in_directory: false
checksum:
  name_template: checksums.txt
snapshot:
  name_template: "{{ .Tag }}-next"

# changelog:
#   sort: asc
#   filters:
#     exclude:
#       - "^docs:"
#       - "^test:"

krews:
  - name: k8surl
    repository:
      owner: jklaw90
      name: k8surl
      branch: main
      token: "{{ .Env.KREW_GITHUB_TOKEN }}"
    url_template: "https://github.com/jklaw90/k8surl/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    commit_author:
      name: Julian Lawrence
      email: julianlawrence@gmail.com
    commit_msg_template: "Krew plugin update for {{ .ProjectName }} version {{ .Tag }}"
    homepage: https://github.com/jklaw90/k8surl
    short_description: Open URLs for Kubernetes resources
    description: |
      This plugin uses dynamically defined commands to launch dashboards and get to the right place in your browser with a single command.
